import { MigrationInterface, QueryRunner } from "typeorm";

export class AddOrderNumberFieldWithDefault1764483675977 implements MigrationInterface {
    name = 'AddOrderNumberFieldWithDefault1764483675977'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "supplier_quotes" DROP CONSTRAINT "FK_ce5981b347cf88c6eea1ce7c12f"`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" DROP CONSTRAINT "supplier_quotes_supplier_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_d16a885aa88447ccfd010e739b0"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "purchase_orders_supplier_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "supplier_evaluations" DROP CONSTRAINT "FK_d3b4256581a6132deb08bef1656"`);
        await queryRunner.query(`ALTER TABLE "supplier_evaluations" DROP CONSTRAINT "supplier_evaluations_supplier_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "addresses_common_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "product_variants_product_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "products_category_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "order_items_crust_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "order_items_filling_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "order_items_order_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "order_items_product_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "order_items_variant_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "order_status_history" DROP CONSTRAINT "order_status_history_created_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "order_status_history" DROP CONSTRAINT "order_status_history_order_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "orders_address_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "orders_common_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "receipts" DROP CONSTRAINT "FK_9545ae8fc5f7714cd8a807dd937"`);
        await queryRunner.query(`ALTER TABLE "receipts" DROP CONSTRAINT "fk_receipts_order"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "user_roles_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "user_roles_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_orders"`);
        await queryRunner.query(`ALTER TABLE "order_reviews" DROP CONSTRAINT "order_reviews_customer_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "order_reviews" DROP CONSTRAINT "order_reviews_order_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_990da5f8a5976f2d02cf60fbdcb"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_fe1f8086b016f319c4f7f389602"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "stock_movements_ingredient_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "stock_movements_order_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "stock_movements_stock_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "stock_movements_supplier_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "stock_movements_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP CONSTRAINT "ingredients_category_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "stocks" DROP CONSTRAINT "FK_61a71d4fda8aebad7760abc6d30"`);
        await queryRunner.query(`ALTER TABLE "stocks" DROP CONSTRAINT "stocks_ingredient_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" DROP CONSTRAINT "FK_ce334dbbd185e082006bcb6a6e5"`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" DROP CONSTRAINT "stock_alerts_ingredient_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" DROP CONSTRAINT "stock_alerts_resolved_by_fkey"`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" DROP CONSTRAINT "stock_alerts_stock_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_permission_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_role_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_common_users_phone"`);
        await queryRunner.query(`DROP INDEX "public"."idx_common_users_cpf"`);
        await queryRunner.query(`DROP INDEX "public"."idx_common_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_addresses_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_addresses_zip"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_categories_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_categories_slug"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_variants_product"`);
        await queryRunner.query(`DROP INDEX "public"."idx_product_variants_size"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_category"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_products_slug"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pizza_crusts_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_crust_fillings_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_items_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_items_product"`);
        await queryRunner.query(`DROP INDEX "public"."idx_admin_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_status_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_status_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_token"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_receipts_order_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_receipts_receipt_number"`);
        await queryRunner.query(`DROP INDEX "public"."idx_receipts_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_permissions_name"`);
        await queryRunner.query(`DROP INDEX "public"."idx_permissions_resource"`);
        await queryRunner.query(`DROP INDEX "public"."idx_roles_name"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_roles_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_roles_role"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_common_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_payments_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_order_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_reviews_order"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_reviews_customer"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_reviews_rating"`);
        await queryRunner.query(`DROP INDEX "public"."idx_movements_ingredient"`);
        await queryRunner.query(`DROP INDEX "public"."idx_movements_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_movements_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_movements_number"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ingredients_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ingredients_group"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ingredients_ean"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ingredients_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_stocks_ingredient"`);
        await queryRunner.query(`DROP INDEX "public"."idx_stocks_expiry"`);
        await queryRunner.query(`DROP INDEX "public"."idx_stocks_batch"`);
        await queryRunner.query(`DROP INDEX "public"."idx_alerts_ingredient"`);
        await queryRunner.query(`DROP INDEX "public"."idx_alerts_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_alerts_resolved"`);
        await queryRunner.query(`DROP INDEX "public"."idx_alerts_priority"`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" DROP CONSTRAINT "supplier_quotes_status_check"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "purchase_orders_payment_method_check"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "purchase_orders_status_check"`);
        await queryRunner.query(`ALTER TABLE "supplier_evaluations" DROP CONSTRAINT "supplier_evaluations_quality_rating_check"`);
        await queryRunner.query(`ALTER TABLE "supplier_evaluations" DROP CONSTRAINT "supplier_evaluations_delivery_rating_check"`);
        await queryRunner.query(`ALTER TABLE "supplier_evaluations" DROP CONSTRAINT "supplier_evaluations_price_rating_check"`);
        await queryRunner.query(`ALTER TABLE "supplier_evaluations" DROP CONSTRAINT "supplier_evaluations_service_rating_check"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "suppliers_status_check"`);
        await queryRunner.query(`ALTER TABLE "order_reviews" DROP CONSTRAINT "order_reviews_overall_rating_check"`);
        await queryRunner.query(`ALTER TABLE "order_reviews" DROP CONSTRAINT "order_reviews_food_quality_check"`);
        await queryRunner.query(`ALTER TABLE "order_reviews" DROP CONSTRAINT "order_reviews_delivery_time_check"`);
        await queryRunner.query(`ALTER TABLE "order_reviews" DROP CONSTRAINT "order_reviews_packaging_check"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "unique_variant_per_product"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "unique_product_slug_per_category"`);
        await queryRunner.query(`ALTER TABLE "order_reviews" DROP CONSTRAINT "order_reviews_order_id_customer_id_key"`);
        await queryRunner.query(`COMMENT ON TABLE "addresses" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "product_categories" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "product_variants" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "products" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "pizza_crusts" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "crust_fillings" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "order_items" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "order_status_history" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "orders" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "receipts" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "order_reviews" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "stock_movements" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "ingredients" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "stocks" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "stock_alerts" IS NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "raffle_id"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "raffles_quantity"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "confirmed_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "started_preparing_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "out_for_delivery_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "delivered_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."supplier_quotes_status_enum" AS ENUM('pending', 'sent', 'received', 'under_analysis', 'approved', 'cancelled', 'converted')`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" ADD "status" "public"."supplier_quotes_status_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "payment_method"`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_payment_method_enum" AS ENUM('pix', 'dinheiro', 'cartao_debito', 'cartao_credito', 'boleto', 'transferencia', 'cheque')`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "payment_method" "public"."purchase_orders_payment_method_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_status_enum" AS ENUM('draft', 'pending_approval', 'approved', 'confirmed', 'in_transit', 'delivered', 'received', 'completed', 'cancelled', 'partial')`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "status" "public"."purchase_orders_status_enum" NOT NULL DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "supplier_evaluations" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supplier_evaluations" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "whatsapp_disponivel" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."suppliers_status_enum" AS ENUM('pre_registered', 'under_review', 'active', 'inactive', 'blocked', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "status" "public"."suppliers_status_enum" NOT NULL DEFAULT 'pre_registered'`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "common_users"."cpf" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "common_users"."birth_date" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "common_users"."phone_alternative" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "common_users"."email" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "common_users"."password_hash" IS NULL`);
        await queryRunner.query(`ALTER TABLE "common_users" ALTER COLUMN "accept_terms" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "common_users"."accept_terms" IS NULL`);
        await queryRunner.query(`ALTER TABLE "common_users" ALTER COLUMN "accept_promotions" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "common_users"."accept_promotions" IS NULL`);
        await queryRunner.query(`ALTER TABLE "common_users" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "common_users" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP COLUMN "delivery_instructions"`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD "delivery_instructions" character varying(500)`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "is_default" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "addresses"."is_default" IS NULL`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "product_categories"."slug" IS NULL`);
        await queryRunner.query(`ALTER TABLE "product_categories" ALTER COLUMN "sort_order" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_categories" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "product_categories"."status" IS NULL`);
        await queryRunner.query(`ALTER TABLE "product_categories" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_categories" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "product_variants"."size" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "product_variants"."label" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "product_variants"."servings" IS NULL`);
        await queryRunner.query(`ALTER TABLE "product_variants" ALTER COLUMN "sort_order" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_variants" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_variants" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_variants" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "products"."type" IS NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "products"."status" IS NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "sort_order" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pizza_crusts" ALTER COLUMN "price_modifier" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pizza_crusts"."price_modifier" IS NULL`);
        await queryRunner.query(`ALTER TABLE "pizza_crusts" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pizza_crusts" ALTER COLUMN "sort_order" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pizza_crusts" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pizza_crusts" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crust_fillings" ALTER COLUMN "price" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crust_fillings" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crust_fillings" ALTER COLUMN "sort_order" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crust_fillings" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crust_fillings" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "order_items"."unit_price" IS NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "crust_price" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "order_items"."crust_price" IS NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "filling_price" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "order_items"."filling_price" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "order_items"."subtotal" IS NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admin_users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "admin_users" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admin_users" DROP CONSTRAINT "admin_users_email_key"`);
        await queryRunner.query(`ALTER TABLE "admin_users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "admin_users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admin_users" ADD CONSTRAINT "UQ_dcd0c8a4b10af9c986e510b9ecc" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "admin_users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "admin_users" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admin_users" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admin_users" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "order_number" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "address_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "status" character varying(20) NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "delivery_token"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "delivery_token" character varying(6)`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."estimated_time" IS NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "delivery_fee" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "discount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "payment_method" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."payment_reference" IS NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "receipts"."receipt_number" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "receipts"."items_json" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "receipts"."subtotal" IS NULL`);
        await queryRunner.query(`ALTER TABLE "receipts" ALTER COLUMN "delivery_fee" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "receipts" ALTER COLUMN "delivery_fee" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "receipts" ALTER COLUMN "discount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "receipts" ALTER COLUMN "discount" SET DEFAULT '0'`);
        await queryRunner.query(`COMMENT ON COLUMN "receipts"."total" IS NULL`);
        await queryRunner.query(`ALTER TABLE "receipts" ALTER COLUMN "was_emailed" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "receipts" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "level" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "is_protected" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "role_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "payments"."order_id" IS NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "status" character varying(20) NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`COMMENT ON COLUMN "payments"."status" IS 'pending | approved | rejected | cancelled | refunded'`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "mercadopago_id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "mercadopago_id" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "pix_qr_code" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "expires_at"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "expires_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "paid_at"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "paid_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "order_reviews"."overall_rating" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "order_reviews"."food_quality" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "order_reviews"."delivery_time" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "order_reviews"."packaging" IS NULL`);
        await queryRunner.query(`ALTER TABLE "order_reviews" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "stock_movements"."movement_number" IS NULL`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."stock_movements_type_enum" AS ENUM('purchase', 'return', 'adjustment_in', 'transfer_in', 'sale', 'loss', 'theft', 'donation', 'adjustment_out', 'transfer_out', 'inventory')`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD "type" "public"."stock_movements_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ALTER COLUMN "unit_cost" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ALTER COLUMN "total_value" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ALTER COLUMN "balance_before" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ALTER COLUMN "balance_after" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ALTER COLUMN "movement_date" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ALTER COLUMN "movement_date" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP CONSTRAINT "ingredients_name_unique"`);
        await queryRunner.query(`ALTER TABLE "ingredients" ALTER COLUMN "internal_code" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "ingredients"."internal_code" IS NULL`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP COLUMN "unit_measure"`);
        await queryRunner.query(`CREATE TYPE "public"."ingredients_unit_measure_enum" AS ENUM('kg', 'g', 'mg', 'ton', 'l', 'ml', 'm3', 'un', 'pc', 'cx', 'pct', 'fardo', 'saco', 'm', 'cm', 'mm')`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD "unit_measure" "public"."ingredients_unit_measure_enum" NOT NULL DEFAULT 'un'`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP COLUMN "group"`);
        await queryRunner.query(`CREATE TYPE "public"."ingredients_group_enum" AS ENUM('ingredient', 'beverage', 'packaging', 'cleaning', 'utensil', 'service')`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD "group" "public"."ingredients_group_enum" NOT NULL DEFAULT 'ingredient'`);
        await queryRunner.query(`ALTER TABLE "ingredients" ALTER COLUMN "sale_price" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ingredients" ALTER COLUMN "profit_margin" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP COLUMN "ncm"`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD "ncm" character varying(8)`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP COLUMN "cest"`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD "cest" character varying(7)`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP COLUMN "cfop"`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD "cfop" character varying(4)`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."ingredients_status_enum" AS ENUM('active', 'inactive', 'blocked')`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD "status" "public"."ingredients_status_enum" NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "ingredients" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ingredients" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ingredients" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ingredients" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "stocks"."quantity" IS NULL`);
        await queryRunner.query(`ALTER TABLE "stocks" ALTER COLUMN "minimum_quantity" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stocks" ALTER COLUMN "maximum_quantity" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stocks" ALTER COLUMN "reserved_quantity" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "stocks"."reserved_quantity" IS NULL`);
        await queryRunner.query(`ALTER TABLE "stocks" ALTER COLUMN "total_value" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stocks" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stocks" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "stocks" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stocks" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" DROP COLUMN "type"`);
        await queryRunner.query(`CREATE TYPE "public"."stock_alerts_type_enum" AS ENUM('low_stock', 'expired', 'near_expiry', 'overstock', 'out_of_stock')`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ADD "type" "public"."stock_alerts_type_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ALTER COLUMN "is_read" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ALTER COLUMN "is_resolved" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ALTER COLUMN "priority" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "stock_alerts"."priority" IS NULL`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" ADD CONSTRAINT "FK_ce5981b347cf88c6eea1ce7c12f" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_d16a885aa88447ccfd010e739b0" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_evaluations" ADD CONSTRAINT "FK_d3b4256581a6132deb08bef1656" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_993b61c821f809513f22908dd1e" FOREIGN KEY ("common_user_id") REFERENCES "common_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_6343513e20e2deab45edfce1316" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "product_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9263386c35b6b242540f9493b00" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_db2d0ea722e16e0fe8ab3bce111" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_038b5d910e1e7ba86067e59e2bf" FOREIGN KEY ("crust_id") REFERENCES "pizza_crusts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_7c207f6f2941cf7ee74342646ab" FOREIGN KEY ("filling_id") REFERENCES "crust_fillings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ADD CONSTRAINT "FK_1ca7d5228cf9dc589b60243933c" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ADD CONSTRAINT "FK_b4a63fbb33ec49b2ae69c220f3d" FOREIGN KEY ("created_by") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_6dd20199c936c8186cd0f4213b8" FOREIGN KEY ("common_user_id") REFERENCES "common_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_d39c53244703b8534307adcd073" FOREIGN KEY ("address_id") REFERENCES "addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receipts" ADD CONSTRAINT "FK_9545ae8fc5f7714cd8a807dd937" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "admin_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_3501da579c5079617a883a1ab62" FOREIGN KEY ("common_user_id") REFERENCES "common_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_b2f7b823a21562eeca20e72b006" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_reviews" ADD CONSTRAINT "FK_97ba7f5a81e581ba466df379dea" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_reviews" ADD CONSTRAINT "FK_60dfca476608d93eac11fd60df6" FOREIGN KEY ("customer_id") REFERENCES "common_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_990da5f8a5976f2d02cf60fbdcb" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_fe1f8086b016f319c4f7f389602" FOREIGN KEY ("stock_id") REFERENCES "stocks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_ba50f4ec0ca8df8e44d805c6533" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_d7fedfd6ee0f4a06648c48631c6" FOREIGN KEY ("user_id") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD CONSTRAINT "FK_78cffcca39dfbf7958936c750f6" FOREIGN KEY ("category_id") REFERENCES "product_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stocks" ADD CONSTRAINT "FK_61a71d4fda8aebad7760abc6d30" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ADD CONSTRAINT "FK_ce334dbbd185e082006bcb6a6e5" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ADD CONSTRAINT "FK_a1b64ea6ad804f75c5edfe5f565" FOREIGN KEY ("stock_id") REFERENCES "stocks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" DROP CONSTRAINT "FK_a1b64ea6ad804f75c5edfe5f565"`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" DROP CONSTRAINT "FK_ce334dbbd185e082006bcb6a6e5"`);
        await queryRunner.query(`ALTER TABLE "stocks" DROP CONSTRAINT "FK_61a71d4fda8aebad7760abc6d30"`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP CONSTRAINT "FK_78cffcca39dfbf7958936c750f6"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_d7fedfd6ee0f4a06648c48631c6"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_ba50f4ec0ca8df8e44d805c6533"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_fe1f8086b016f319c4f7f389602"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP CONSTRAINT "FK_990da5f8a5976f2d02cf60fbdcb"`);
        await queryRunner.query(`ALTER TABLE "order_reviews" DROP CONSTRAINT "FK_60dfca476608d93eac11fd60df6"`);
        await queryRunner.query(`ALTER TABLE "order_reviews" DROP CONSTRAINT "FK_97ba7f5a81e581ba466df379dea"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_b2f7b823a21562eeca20e72b006"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_3501da579c5079617a883a1ab62"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "receipts" DROP CONSTRAINT "FK_9545ae8fc5f7714cd8a807dd937"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_d39c53244703b8534307adcd073"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_6dd20199c936c8186cd0f4213b8"`);
        await queryRunner.query(`ALTER TABLE "order_status_history" DROP CONSTRAINT "FK_b4a63fbb33ec49b2ae69c220f3d"`);
        await queryRunner.query(`ALTER TABLE "order_status_history" DROP CONSTRAINT "FK_1ca7d5228cf9dc589b60243933c"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_7c207f6f2941cf7ee74342646ab"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_038b5d910e1e7ba86067e59e2bf"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_db2d0ea722e16e0fe8ab3bce111"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9263386c35b6b242540f9493b00"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_6343513e20e2deab45edfce1316"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_993b61c821f809513f22908dd1e"`);
        await queryRunner.query(`ALTER TABLE "supplier_evaluations" DROP CONSTRAINT "FK_d3b4256581a6132deb08bef1656"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_d16a885aa88447ccfd010e739b0"`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" DROP CONSTRAINT "FK_ce5981b347cf88c6eea1ce7c12f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "stock_alerts"."priority" IS 'low, medium, high, critical'`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ALTER COLUMN "priority" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ALTER COLUMN "is_resolved" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ALTER COLUMN "is_read" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."stock_alerts_type_enum"`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ADD "type" character varying(30) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stocks" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "stocks" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stocks" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "stocks" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stocks" ALTER COLUMN "total_value" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "stocks"."reserved_quantity" IS 'Quantidade reservada em pedidos'`);
        await queryRunner.query(`ALTER TABLE "stocks" ALTER COLUMN "reserved_quantity" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stocks" ALTER COLUMN "maximum_quantity" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stocks" ALTER COLUMN "minimum_quantity" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "stocks"."quantity" IS 'Quantidade atual em estoque'`);
        await queryRunner.query(`ALTER TABLE "ingredients" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "ingredients" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ingredients" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "ingredients" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."ingredients_status_enum"`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD "status" character varying(20) NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP COLUMN "cfop"`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD "cfop" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP COLUMN "cest"`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD "cest" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP COLUMN "ncm"`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD "ncm" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "ingredients" ALTER COLUMN "profit_margin" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ingredients" ALTER COLUMN "sale_price" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP COLUMN "group"`);
        await queryRunner.query(`DROP TYPE "public"."ingredients_group_enum"`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD "group" character varying(20) NOT NULL DEFAULT 'ingredient'`);
        await queryRunner.query(`ALTER TABLE "ingredients" DROP COLUMN "unit_measure"`);
        await queryRunner.query(`DROP TYPE "public"."ingredients_unit_measure_enum"`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD "unit_measure" character varying(20) NOT NULL DEFAULT 'un'`);
        await queryRunner.query(`COMMENT ON COLUMN "ingredients"."internal_code" IS 'Código interno único (ING-YYYYMMDD-XXX)'`);
        await queryRunner.query(`ALTER TABLE "ingredients" ALTER COLUMN "internal_code" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD CONSTRAINT "ingredients_name_unique" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ALTER COLUMN "movement_date" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ALTER COLUMN "movement_date" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ALTER COLUMN "balance_after" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ALTER COLUMN "balance_before" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ALTER COLUMN "total_value" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ALTER COLUMN "unit_cost" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stock_movements" DROP COLUMN "type"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movements_type_enum"`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD "type" character varying(30) NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "stock_movements"."movement_number" IS 'Número único (MOV-YYYYMMDD-XXX)'`);
        await queryRunner.query(`ALTER TABLE "order_reviews" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "order_reviews"."packaging" IS 'Qualidade da embalagem (1-5)'`);
        await queryRunner.query(`COMMENT ON COLUMN "order_reviews"."delivery_time" IS 'Tempo de entrega (1-5)'`);
        await queryRunner.query(`COMMENT ON COLUMN "order_reviews"."food_quality" IS 'Qualidade da comida (1-5)'`);
        await queryRunner.query(`COMMENT ON COLUMN "order_reviews"."overall_rating" IS 'Nota geral (1-5)'`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "paid_at"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "paid_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "expires_at"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "expires_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "pix_qr_code" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "mercadopago_id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "mercadopago_id" character varying(255)`);
        await queryRunner.query(`COMMENT ON COLUMN "payments"."status" IS 'pending | approved | rejected | cancelled | refunded'`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "status" character varying(50) NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`COMMENT ON COLUMN "payments"."order_id" IS 'Referência do pedido vinculado ao pagamento'`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "role_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_roles" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "admin_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "is_protected" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "level" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "receipts" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "receipts" ALTER COLUMN "was_emailed" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "receipts"."total" IS 'Valor final = subtotal + delivery_fee - discount'`);
        await queryRunner.query(`ALTER TABLE "receipts" ALTER COLUMN "discount" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "receipts" ALTER COLUMN "discount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "receipts" ALTER COLUMN "delivery_fee" SET DEFAULT 0.00`);
        await queryRunner.query(`ALTER TABLE "receipts" ALTER COLUMN "delivery_fee" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "receipts"."subtotal" IS 'Soma dos itens sem taxa de entrega'`);
        await queryRunner.query(`COMMENT ON COLUMN "receipts"."items_json" IS 'Snapshot dos itens do pedido em JSON'`);
        await queryRunner.query(`COMMENT ON COLUMN "receipts"."receipt_number" IS 'Número único do comprovante (REC-YYYYMMDD-XXXX)'`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."payment_reference" IS 'Referência do pagamento (temporário até refatoração)'`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "payment_method" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "discount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "delivery_fee" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "orders"."estimated_time" IS 'Tempo estimado de entrega em minutos'`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "delivery_token"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "delivery_token" character varying(10)`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "status" character varying(50) DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "address_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "order_number" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admin_users" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admin_users" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admin_users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "admin_users" ADD "password" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admin_users" DROP CONSTRAINT "UQ_dcd0c8a4b10af9c986e510b9ecc"`);
        await queryRunner.query(`ALTER TABLE "admin_users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "admin_users" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "admin_users" ADD CONSTRAINT "admin_users_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "admin_users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "admin_users" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "order_items"."subtotal" IS 'Total do item (quantidade × (unit_price + crust_price + filling_price))'`);
        await queryRunner.query(`COMMENT ON COLUMN "order_items"."filling_price" IS 'Preço adicional do recheio'`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "filling_price" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "order_items"."crust_price" IS 'Preço adicional da borda'`);
        await queryRunner.query(`ALTER TABLE "order_items" ALTER COLUMN "crust_price" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "order_items"."unit_price" IS 'Preço da variação do produto'`);
        await queryRunner.query(`ALTER TABLE "crust_fillings" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crust_fillings" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crust_fillings" ALTER COLUMN "sort_order" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crust_fillings" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "crust_fillings" ALTER COLUMN "price" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pizza_crusts" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pizza_crusts" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pizza_crusts" ALTER COLUMN "sort_order" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pizza_crusts" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "pizza_crusts"."price_modifier" IS 'Valor adicional (0 para tradicional)'`);
        await queryRunner.query(`ALTER TABLE "pizza_crusts" ALTER COLUMN "price_modifier" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "sort_order" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "products"."status" IS 'active, inactive, out_of_stock'`);
        await queryRunner.query(`ALTER TABLE "products" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "products"."type" IS 'simple (bebida), pizza (com variações)'`);
        await queryRunner.query(`ALTER TABLE "product_variants" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_variants" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_variants" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_variants" ALTER COLUMN "sort_order" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "product_variants"."servings" IS 'Número de pedaços (pizzas)'`);
        await queryRunner.query(`COMMENT ON COLUMN "product_variants"."label" IS 'Ex: Pequena - 4 pedaços'`);
        await queryRunner.query(`COMMENT ON COLUMN "product_variants"."size" IS 'small, medium, large, unique'`);
        await queryRunner.query(`ALTER TABLE "product_categories" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_categories" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "product_categories"."status" IS 'active, inactive'`);
        await queryRunner.query(`ALTER TABLE "product_categories" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_categories" ALTER COLUMN "sort_order" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "product_categories"."slug" IS 'URL amigável (ex: pizzas-salgadas)'`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "addresses"."is_default" IS 'Define se é o endereço padrão do cliente'`);
        await queryRunner.query(`ALTER TABLE "addresses" ALTER COLUMN "is_default" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP COLUMN "delivery_instructions"`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD "delivery_instructions" text`);
        await queryRunner.query(`ALTER TABLE "common_users" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "common_users" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "common_users"."accept_promotions" IS 'Aceitou receber promoções'`);
        await queryRunner.query(`ALTER TABLE "common_users" ALTER COLUMN "accept_promotions" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "common_users"."accept_terms" IS 'Aceitou termos de uso (LGPD)'`);
        await queryRunner.query(`ALTER TABLE "common_users" ALTER COLUMN "accept_terms" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "common_users"."password_hash" IS 'Senha hash bcrypt para login'`);
        await queryRunner.query(`COMMENT ON COLUMN "common_users"."email" IS 'Email do cliente (opcional)'`);
        await queryRunner.query(`COMMENT ON COLUMN "common_users"."phone_alternative" IS 'Telefone alternativo'`);
        await queryRunner.query(`COMMENT ON COLUMN "common_users"."birth_date" IS 'Data de nascimento do cliente'`);
        await queryRunner.query(`COMMENT ON COLUMN "common_users"."cpf" IS 'CPF do cliente (formato: 000.000.000-00)'`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."suppliers_status_enum"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "status" character varying(20) DEFAULT 'pre_registered'`);
        await queryRunner.query(`ALTER TABLE "suppliers" ALTER COLUMN "whatsapp_disponivel" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supplier_evaluations" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "supplier_evaluations" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_status_enum"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "status" character varying(20) DEFAULT 'draft'`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "payment_method"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_payment_method_enum"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "payment_method" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."supplier_quotes_status_enum"`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" ADD "status" character varying(20) DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "delivered_at"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "out_for_delivery_at"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "started_preparing_at"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "confirmed_at"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "raffles_quantity" integer`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "raffle_id" character varying(255)`);
        await queryRunner.query(`COMMENT ON TABLE "stock_alerts" IS 'Alertas automáticos de estoque'`);
        await queryRunner.query(`COMMENT ON TABLE "stocks" IS 'Controle de estoque por ingrediente e lote'`);
        await queryRunner.query(`COMMENT ON TABLE "ingredients" IS 'Cadastro de ingredientes, bebidas e insumos'`);
        await queryRunner.query(`COMMENT ON TABLE "stock_movements" IS 'Histórico completo de movimentações de estoque'`);
        await queryRunner.query(`COMMENT ON TABLE "order_reviews" IS 'Avaliações dos pedidos pelos clientes'`);
        await queryRunner.query(`COMMENT ON TABLE "receipts" IS 'Comprovantes de compra gerados após pagamento'`);
        await queryRunner.query(`COMMENT ON TABLE "orders" IS 'Pedidos realizados pelos clientes'`);
        await queryRunner.query(`COMMENT ON TABLE "order_status_history" IS 'Histórico de mudanças de status do pedido'`);
        await queryRunner.query(`COMMENT ON TABLE "order_items" IS 'Itens individuais de cada pedido'`);
        await queryRunner.query(`COMMENT ON TABLE "crust_fillings" IS 'Recheios para bordas Vulcão/Trançada'`);
        await queryRunner.query(`COMMENT ON TABLE "pizza_crusts" IS 'Tipos de borda (Tradicional, Vulcão, Trançada)'`);
        await queryRunner.query(`COMMENT ON TABLE "products" IS 'Produtos do cardápio (pizzas, bebidas, etc.)'`);
        await queryRunner.query(`COMMENT ON TABLE "product_variants" IS 'Variações de tamanho/preço (P/M/G para pizzas)'`);
        await queryRunner.query(`COMMENT ON TABLE "product_categories" IS 'Categorias de produtos (Pizzas, Bebidas, etc.)'`);
        await queryRunner.query(`COMMENT ON TABLE "addresses" IS 'Endereços de entrega dos clientes'`);
        await queryRunner.query(`ALTER TABLE "order_reviews" ADD CONSTRAINT "order_reviews_order_id_customer_id_key" UNIQUE ("order_id", "customer_id")`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "unique_product_slug_per_category" UNIQUE ("category_id", "slug")`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "unique_variant_per_product" UNIQUE ("product_id", "size")`);
        await queryRunner.query(`ALTER TABLE "order_reviews" ADD CONSTRAINT "order_reviews_packaging_check" CHECK (((packaging >= 1) AND (packaging <= 5)))`);
        await queryRunner.query(`ALTER TABLE "order_reviews" ADD CONSTRAINT "order_reviews_delivery_time_check" CHECK (((delivery_time >= 1) AND (delivery_time <= 5)))`);
        await queryRunner.query(`ALTER TABLE "order_reviews" ADD CONSTRAINT "order_reviews_food_quality_check" CHECK (((food_quality >= 1) AND (food_quality <= 5)))`);
        await queryRunner.query(`ALTER TABLE "order_reviews" ADD CONSTRAINT "order_reviews_overall_rating_check" CHECK (((overall_rating >= 1) AND (overall_rating <= 5)))`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "suppliers_status_check" CHECK (((status)::text = ANY ((ARRAY['pre_registered'::character varying, 'under_review'::character varying, 'active'::character varying, 'inactive'::character varying, 'blocked'::character varying, 'rejected'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "supplier_evaluations" ADD CONSTRAINT "supplier_evaluations_service_rating_check" CHECK (((service_rating >= 1) AND (service_rating <= 5)))`);
        await queryRunner.query(`ALTER TABLE "supplier_evaluations" ADD CONSTRAINT "supplier_evaluations_price_rating_check" CHECK (((price_rating >= 1) AND (price_rating <= 5)))`);
        await queryRunner.query(`ALTER TABLE "supplier_evaluations" ADD CONSTRAINT "supplier_evaluations_delivery_rating_check" CHECK (((delivery_rating >= 1) AND (delivery_rating <= 5)))`);
        await queryRunner.query(`ALTER TABLE "supplier_evaluations" ADD CONSTRAINT "supplier_evaluations_quality_rating_check" CHECK (((quality_rating >= 1) AND (quality_rating <= 5)))`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_status_check" CHECK (((status)::text = ANY ((ARRAY['draft'::character varying, 'pending_approval'::character varying, 'approved'::character varying, 'confirmed'::character varying, 'in_transit'::character varying, 'delivered'::character varying, 'received'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'partial'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_payment_method_check" CHECK (((payment_method)::text = ANY ((ARRAY['pix'::character varying, 'dinheiro'::character varying, 'cartao_debito'::character varying, 'cartao_credito'::character varying, 'boleto'::character varying, 'transferencia'::character varying, 'cheque'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" ADD CONSTRAINT "supplier_quotes_status_check" CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'sent'::character varying, 'received'::character varying, 'under_analysis'::character varying, 'approved'::character varying, 'cancelled'::character varying, 'converted'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "idx_alerts_priority" ON "stock_alerts" ("priority") `);
        await queryRunner.query(`CREATE INDEX "idx_alerts_resolved" ON "stock_alerts" ("is_resolved") `);
        await queryRunner.query(`CREATE INDEX "idx_alerts_type" ON "stock_alerts" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_alerts_ingredient" ON "stock_alerts" ("ingredient_id") `);
        await queryRunner.query(`CREATE INDEX "idx_stocks_batch" ON "stocks" ("batch_number") `);
        await queryRunner.query(`CREATE INDEX "idx_stocks_expiry" ON "stocks" ("expiry_date") `);
        await queryRunner.query(`CREATE INDEX "idx_stocks_ingredient" ON "stocks" ("ingredient_id") `);
        await queryRunner.query(`CREATE INDEX "idx_ingredients_deleted" ON "ingredients" ("deleted_at") `);
        await queryRunner.query(`CREATE INDEX "idx_ingredients_ean" ON "ingredients" ("ean") `);
        await queryRunner.query(`CREATE INDEX "idx_ingredients_group" ON "ingredients" ("group") `);
        await queryRunner.query(`CREATE INDEX "idx_ingredients_status" ON "ingredients" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_movements_number" ON "stock_movements" ("movement_number") `);
        await queryRunner.query(`CREATE INDEX "idx_movements_date" ON "stock_movements" ("movement_date") `);
        await queryRunner.query(`CREATE INDEX "idx_movements_type" ON "stock_movements" ("type") `);
        await queryRunner.query(`CREATE INDEX "idx_movements_ingredient" ON "stock_movements" ("ingredient_id") `);
        await queryRunner.query(`CREATE INDEX "idx_order_reviews_rating" ON "order_reviews" ("overall_rating") `);
        await queryRunner.query(`CREATE INDEX "idx_order_reviews_customer" ON "order_reviews" ("customer_id") `);
        await queryRunner.query(`CREATE INDEX "idx_order_reviews_order" ON "order_reviews" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_order_id" ON "payments" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_status" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_payments_common_user" ON "payments" ("common_user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_roles_role" ON "user_roles" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_roles_user" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_roles_name" ON "roles" ("name") `);
        await queryRunner.query(`CREATE INDEX "idx_permissions_resource" ON "permissions" ("resource") `);
        await queryRunner.query(`CREATE INDEX "idx_permissions_name" ON "permissions" ("name") `);
        await queryRunner.query(`CREATE INDEX "idx_receipts_created_at" ON "receipts" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_receipts_receipt_number" ON "receipts" ("receipt_number") `);
        await queryRunner.query(`CREATE INDEX "idx_receipts_order_id" ON "receipts" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_created" ON "orders" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_token" ON "orders" ("delivery_token") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_status" ON "orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_user" ON "orders" ("common_user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_order_status_created" ON "order_status_history" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_order_status_order" ON "order_status_history" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_admin_users_email" ON "admin_users" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_order_items_product" ON "order_items" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "idx_order_items_order" ON "order_items" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "idx_crust_fillings_status" ON "crust_fillings" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_pizza_crusts_status" ON "pizza_crusts" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_products_slug" ON "products" ("slug") `);
        await queryRunner.query(`CREATE INDEX "idx_products_status" ON "products" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_products_category" ON "products" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "idx_product_variants_size" ON "product_variants" ("size") `);
        await queryRunner.query(`CREATE INDEX "idx_product_variants_product" ON "product_variants" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "idx_product_categories_slug" ON "product_categories" ("slug") `);
        await queryRunner.query(`CREATE INDEX "idx_product_categories_status" ON "product_categories" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_addresses_zip" ON "addresses" ("zip_code") `);
        await queryRunner.query(`CREATE INDEX "idx_addresses_user" ON "addresses" ("common_user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_common_users_email" ON "common_users" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_common_users_cpf" ON "common_users" ("cpf") `);
        await queryRunner.query(`CREATE INDEX "idx_common_users_phone" ON "common_users" ("phone") `);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ADD CONSTRAINT "stock_alerts_stock_id_fkey" FOREIGN KEY ("stock_id") REFERENCES "stocks"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ADD CONSTRAINT "stock_alerts_resolved_by_fkey" FOREIGN KEY ("resolved_by") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ADD CONSTRAINT "stock_alerts_ingredient_id_fkey" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_alerts" ADD CONSTRAINT "FK_ce334dbbd185e082006bcb6a6e5" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stocks" ADD CONSTRAINT "stocks_ingredient_id_fkey" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stocks" ADD CONSTRAINT "FK_61a71d4fda8aebad7760abc6d30" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ingredients" ADD CONSTRAINT "ingredients_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "product_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_supplier_id_fkey" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_stock_id_fkey" FOREIGN KEY ("stock_id") REFERENCES "stocks"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "stock_movements_ingredient_id_fkey" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_fe1f8086b016f319c4f7f389602" FOREIGN KEY ("stock_id") REFERENCES "stocks"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_movements" ADD CONSTRAINT "FK_990da5f8a5976f2d02cf60fbdcb" FOREIGN KEY ("ingredient_id") REFERENCES "ingredients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_reviews" ADD CONSTRAINT "order_reviews_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_reviews" ADD CONSTRAINT "order_reviews_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "common_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_orders" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "admin_users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receipts" ADD CONSTRAINT "fk_receipts_order" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receipts" ADD CONSTRAINT "FK_9545ae8fc5f7714cd8a807dd937" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "orders_common_user_id_fkey" FOREIGN KEY ("common_user_id") REFERENCES "common_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "orders_address_id_fkey" FOREIGN KEY ("address_id") REFERENCES "addresses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ADD CONSTRAINT "order_status_history_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ADD CONSTRAINT "order_status_history_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "order_items_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "order_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "order_items_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "order_items_filling_id_fkey" FOREIGN KEY ("filling_id") REFERENCES "crust_fillings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "order_items_crust_id_fkey" FOREIGN KEY ("crust_id") REFERENCES "pizza_crusts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "products_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "product_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "product_variants_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "addresses_common_user_id_fkey" FOREIGN KEY ("common_user_id") REFERENCES "common_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_evaluations" ADD CONSTRAINT "supplier_evaluations_supplier_id_fkey" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_evaluations" ADD CONSTRAINT "FK_d3b4256581a6132deb08bef1656" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "purchase_orders_supplier_id_fkey" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_d16a885aa88447ccfd010e739b0" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" ADD CONSTRAINT "supplier_quotes_supplier_id_fkey" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_quotes" ADD CONSTRAINT "FK_ce5981b347cf88c6eea1ce7c12f" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
