compressionLevel: mixed

enableGlobalCache: true

enableImmutableInstalls: false

enableNetwork: true

httpTimeout: 120000

networkConcurrency: 8

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-classic.cjs
